### PR TITLE
Add test for idempotence

### PR DESCRIPTION
**Pull request by enricomarino**

### CODE REVIEW

**Comment by enricomarino** [comment]
This test should increase the coverage in [#32](https://github.com/ipld/js-cid/pull/32)

**Comment by diasdavid** [comment]
@enricomarino it is failing in CI https://travis-ci.org/ipld/js-cid/jobs/237969800#L506-L510

**Comment by enricomarino** [comment]
You're right. This pull request, that adds a test, actually miss the code to test (added in the previous pull request).
I'm sorry. I should re-pull the request merging the this pull request (the test) with the previous one (the code to test).

**Comment by diasdavid** [comment]
prefect. Yeah, pushing features with the test on the same PR is the best practice. Thanks @enricomarino :)

**Pull request closed without merging**
